SSR = ["grandorder servant servant Jeanne-darc-Alter", "grandorder servant Scathach" , "grandorder servant Altria-Pendragon", "grandorder servant Okita-Souji", "grandorder servant Nero-Claudius-Bride", "grandorder servant Mordred", "grandorder servant Miyamoto-Musashi", "grandorder servant Sigurd", "grandorder servant Dioscuri", 
       "grandorder servant Senji-Muramasa", "grandorder servant Gilgamesh", "grandorder servant Orion", "grandorder servant Nikola-Tesla", "grandorder servant Arjuna", "grandorder servant Ishtar", "grandorder servant Karna","grandorder servant Karna", "grandorder servant Enkidu", "grandorder servant Ereshkigal", 
       "grandorder servant Medb", "grandorder servant Ozymandias", "grandorder servant Achilles", "grandorder servant Europa", "grandorder servant Odysseus", "grandorder servant Zhuge-Liang-El-Melloi-II", "grandorder servant Tamamo-No-Mae", "grandorder servant Leonardo-Da-Vinci", "grandorder servant Merlin", "grandorder servant Solomon", "grandorder servant Anastasia", "grandorder servant Scathach-Skadi",
       "grandorder servant Jack-Ripper", "grandorder servant Mysterious-Heroine-X", "grandorder servant Shuten-Douji", "grandorder servant First-Hassan", "grandorder servant Kama", "grandorder servant Li-Shuwen","grandorder servant VladIII", "grandorder servant MysteriousHeroineXAlter", "grandorder servant Jeanne-dArc", "grandorder servant SherlockHolmes",
       "grandorder servant Qin-Shi-Huang", "grandorder servant Himiko", "grandorder servant Edmond-Dantes", "grandorder servant Taira-No-Kagekiyo", "grandorder servant Sessyoin-Kiara", "grandorder servant Ganesha","grandorder servant Meltryllis", "grandorder servant PassionLip","grandorder servant Sitonai", "grandorder servant Kingprotea", "grandorder servant Abigail-Williams",
       "grandorder servant Katsushika-Hokusai", "grandorder servant Yang-Guifei","grandorder servant Van-Gogh",
       "arknights operator Surtr", "arknights operator Skadi", "arknights operator Chen", "arknights operator Exusiai", "arknights operator Shining", "arknights operator Nightingale", 
       "arknights operator Eyjafjalla", "arknights operator Angelina", "arknights operator Silverash", "arknights operator Schwarz", "arknights operator Magallan", "arknights operator Mostima", 
       "arknights operator Blaze", "arknights operator Nian", "arknights operator Ceobe", "arknights operator Bagpipe", "arknights operator W", "arknights operator Weedy", "arknights operator Thorns", "arknights operator Eunectes",
       "arknights operator Blemishine", "arknights operator Rosmontis", "arknights operator Mudrock",
       "girlsfrontline t-doll 416", "girlsfrontline t-doll WA2000", "girlsfrontline t-doll Suomi", "girlsfrontline t-doll Vector", "girlsfrontline t-doll MP7", "girlsfrontline t-doll FAL", "girlsfrontline t-doll Five-Seven", "girlsfrontline t-doll Negev", "girlsfrontline t-doll OTs-14", "girlsfrontline t-doll G11", "girlsfrontline t-doll UMP45", "girlsfrontline t-doll UMP9", "girlsfrontline t-doll RO635", "girlsfrontline t-doll M4A1", "girlsfrontline t-doll ST-AR-15", "girlsfrontline t-doll M4-SOPMOD-II", "girlsfrontline t-doll M16A1",
       "girlsfrontline t-doll RFB", "girlsfrontline t-doll SAT8", "girlsfrontline t-doll K2", "girlsfrontline t-doll Carcano-M1891", "girlsfrontline t-doll Carcano-M9138", "girlsfrontline t-doll AN94", "girlsfrontline t-doll AK12", "girlsfrontline t-doll JS-9", "girlsfrontline t-doll K11", "girlsfrontline t-doll P90", "girlsfrontline t-doll Lewis-Gun", "girlsfrontline t-doll MG36", "girlsfrontline t-doll PA-15", "girlsfrontline t-doll R93", "girlsfrontline t-doll RPK-16", "girlsfrontline t-doll AK-15", "girlsfrontline t-doll AK-Alfa",
       "genshin Jean","genshin Diluc", "genshin Qiqi", "genshin Keqing", "genshin Mona", "genshin Venti", "genshin Klee", "genshin Zhongli", "genshin Tartaglia", "genshin Albedo", "genshin Ganyu", "genshin Hu_Tao", "genshin Xiao",
       "genshin Eula", "genshin Ayaka", 
       "alchemy Beryl","alchemy Carleen" ,"alchemy Charon" ,"alchemy Connolly" ,"alchemy Eicy" ,"alchemy Eve" ,"alchemy Fleur" ,"alchemy Gabriel" ,"alchemy Gronru" ,"alchemy Hiiro" ,"alchemy Irridon" ,"alchemy Jona" ,"alchemy Michael" ,"alchemy Migard" ,"alchemy Nikinis" ,"alchemy Raphael" ,"alchemy Sariel" ,"alchemy Sharona" ,"alchemy Sinsa" ,"alchemy Uriel" ,"alchemy Victoria" ,"alchemy Wrath" , "SSR"
       ]
SR = ["grandorder servant Nero-Claudius","grandorder servant Altria-Pendragon-Alter", "grandorder servant Rama", "grandorder servant Lancelot", "grandorder servant Archer-Inferno", "grandorder servant EMIYA", "grandorder servant Atalante", "grandorder servant Tristan", "grandorder servant Oda-Nobunaga", "grandorder servant Calamity-Jane","grandorder servant Nezha", "grandorder servant Parvati", "grandorder servant Elice-Utsumi",
      "grandorder servant Marie-Antoinette", "grandorder servant Astolfo", "grandorder servant Helena-Blavatsky","grandorder servant Thomas-Edison", "grandorder servant Caster-Okeanos", "grandorder servant Carmilla", "grandorder servant Yu-Mei-Ren", "grandorder servant Heracles", "grandorder servant Beowulf", "grandorder servant Frankenstein", "grandorder servant Astraea",
      "grandorder servant Gorgon", "grandorder servant BB",
      "arknights operator Texas", "arknights operator Ptilopsis", "arknights operator Silence", "arknights operator Warfarin", "arknights operator Skyfire", "arknights operator Nightmare", "arknights operator Projekt-Red",
      "arknights operator Manticore", "arknights operator FEater", "arknights operator Blue-Poison", "arknights operator Meteorite", "arknights operator Platinum", "arknights operator Sora", "arknights operator Specter", "arknights operator Lappland",
      "arknights operator Nearl", "arknights operator Liskarm", "arknights operator Swire", "arknights operator Astesia", "arknights operator Flamebringer", "arknights operator Executor", "arknights operator Reed", "arknights operator Greythroat", "arknights operator Snowsant",
      "arknights operator Elysium", "arknights operator Tsukinogi", "arknights operator Leonhardt", "arknights operator Ayarscarpe", "arknights operator Beeswax", "arknights operator April", "arknights operator Whisperain",
      "girlsfrontline t-doll SAA","girlsfrontline t-doll Springfield","girlsfrontline t-doll SVD", "girlsfrontline t-doll M1918-BAR", "girlsfrontline t-doll SPAS-12", "girlsfrontline t-doll Honey-Badger", "girlsfrontline t-doll EM-2",
      "genshin Amber", "genshin Barbara", "genshin Bennet", "genshin Beidou", "genshin Chongyun", "genshin Diona", "genshin Kaeya", "genshin Fischl", "genshin Lisa", "genshin Ningguang", "genshin Noelle", "genshin Razor", "genshin Rosaria",
      "genshin Sucrose", "genshin Xiangling", "genshin Xinyang", "genshin Xingqiu", "genshin Yanfei", 
      "alchemy Areia" ,"alchemy Barbara" ,"alchemy Barton" ,"alchemy Beverly" ,"alchemy Bonacie" ,"alchemy Corax" ,"alchemy Dawn" ,"alchemy Dayna" ,"alchemy Hydrad" ,"alchemy Istvan" ,"alchemy Kleken" ,"alchemy Leona" ,"alchemy Louise" ,"alchemy Maggie" ,"alchemy Mia" ,"alchemy Pact" ,"alchemy Philyshy" ,"alchemy Schwartz" ,"SR"
      ]
R = ["grandorder servant Bedivere", "grandorder servant Robin-Hood", "grandorder servant Euryale", "grandorder servant David", "grandorder servant Cu-Chulainn", "grandorder servant Hector", "grandorder servant Medusa", "grandorder servant Ushiwakamaru", "grandorder servant Medea", "grandorder servant Gilles-De-Rais",
     "grandorder servant Charles-Babbage", "grandorder servant Asclepius", "grandorder servant Henry-Jekyll-Hyde", "grandorder servant Hassan-Serenity", "grandorder servant Lu-Bu-Fengxian", "grandorder servant Kiyohime", "grandorder servant Antonio-Salieri",
     "arknights operator Courier", "arknights operator Scavenger", "arknights operator Vigna", "arknights operator Gravel", "arknights operator Jessica", "arknights operator Deepcolor", "arknights operator Dobermann", "arknights operator Estelle", "arknights operator Beehunter", 
     "arknights operator Mousse", "arknights operator Frostleaf", "arknights operator Cuora", "arknights operator Matterhorn", "arknights operator Myrtle", "arknights operator Ethan", "arknights operator May", "arknights operator Ambriel", "arknights operator Utage","arknights operator Cutter", 
     "arknights operator Jaye", "arknights operator Podenco", "arknights operator Arene", "arknights operator Jackie",
     "girlsfrontline t-doll C96", "girlsfrontline t-doll Ingram", "girlsfrontline t-doll Skorpion", "girlsfrontline t-doll Sten-MkII", "girlsfrontline t-doll Micro-Uzi", "girlsfrontline t-doll M14", "girlsfrontline t-doll M249-SAW", "girlsfrontline t-doll Type88", "girlsfrontline t-doll Magal", "girlsfrontline t-doll Steyr-Scout", 
     "alchemy Alice" ,"alchemy Brock" ,"alchemy Chandra" ,"alchemy Chloe" ,"alchemy Jane" ,"alchemy Kafka" ,"alchemy Ms_Blanc" ,"alchemy Nadine" ,"alchemy Uriah" ,"Rare"
     ]
UC = ["grandorder servant Paris", "grandorder servant Musashibou-Benkei", "grandorder servant Leonidas", "grandorder servant Georgios", "grandorder servant Edward-Teach", "grandorder servant Hans-Christian-Andersen", "grandorder servant William-Shakespeare", "grandorder servant Chen-Gong", "grandorder servant Hassan-Cursed-Arm", "grandorder servant Phantom-Opera",
      "grandorder servant Caligula", "grandorder servant Eric-Bloodaxe","grandorder servant Anra-Mainiiu",
      "arknights operator Fang", "arknights operator Plume", "arknights operator Hibiscus", "arknights operator Lava", "arknights operator Kroos", "arknights operator Steward", "arknights operator Melantha", "arknights operator Beagle", "arknights operator Cardigan", "arknights operator Midnight",
      "arknights operator Spot", "arknights operator Adnachiel", 
      "alchemy Amy" ,"alchemy Angel" ,"alchemy Chainsaw_Rick" ,"alchemy Zoya" ,"alchemy Tiny_One" ,"alchemy White_Dwarf", "Uncommon"
      ]
C = ["grandorder servant Jason","grandorder servant Arash", "grandorder servant Gareth", "grandorder servant Bartholomew-Roberts", "grandorder servant Wolfgang-Amadeus-Mozart","grandorder servant Sasaki-Kojiro", "grandorder servant Charlotte-Corday", "grandorder servant Spartacus", "grandorder servant Asterios", "grandorder servant Paul-Bunyan",
     "arknights operator Yato", "arknights operator Durin", "arknights operator 12F", "arknights operator Rangers", "arknights operator Noir-Corne", "arknights operator Lancet-2", "arknights operator Castle-3", "arknights operator Thrm-EX",
     "girlsfrontline t-doll LWMMG","girlsfrontline t-doll M1911", "girlsfrontline t-doll M1895", "girlsfrontline t-doll IDW", "Common"
     ]

GachaList = [SSR, SR, R, UC, C]